alias ..='cd ..'
alias ...='cd ../../../'
alias ....='cd ../../../../'
alias .....='cd ../../../../'
alias .4='cd ../../../../'
alias .5='cd ../../../../..'
alias aliases="bat $HOME/.bash_aliases"
alias blkid_="blkid -o list"
alias buu="brew update && brew upgrade"
alias cat='bat'
alias chown='chown -v --preserve-root'
alias chmod='chmod -v --preserve-root'
alias chgrp='chgrp --preserve-root'
alias chmox="chmod +x --preserve-root"
alias cp='cp -iv'
alias cpv="rsync -ah --info=progress2 --no-inc-recursive --stats" 
alias dcla="docker container ls -a "
alias df='df -h'
alias diff='delta'
alias dlf="docker logs -f --tail 1000 "
alias du='du -ch'
alias egrep='egrep --color=auto'
alias ff="rg --files --hidden --glob '!.git' | fzf --preview 'bat --style=numbers --color=always --line-range :200 {}'"
alias fs="stat -f \"%z bytes\""
alias fgrep='fgrep --color=auto'
alias ga='git add'
alias gaa='git add --all'
alias gap='git add --patch'
alias gbr='git branch'
alias gbra='git branch --all'
alias gc='git commit -m'
alias gca='git commit --amend'
alias gcan='git commit --amend --no-edit'
alias gco='git checkout'
alias gcob='git checkout -b
alias gd='git diff'
alias gds='git diff --staged'
alias gl='git log --oneline --decorate --graph'
alias gll='git log --oneline'
alias glast='git log -1 HEAD --stat'
alias gp='git push'
alias gpf='git push --force-with-lease'
alias gpl='git pull
alias grba='git rebase --abort''
alias grbc='git rebase --continue'
alias grep='grep --color=auto'
alias gst='git stash'
alias gstp='git stash pop
alias ipaddr="ip -c a | sed -e 's/\// \//g'"
alias joke='command wget -U "curl/7.55.1" -o /dev/null -qO - https://icanhazdadjoke.com || printf "No jokes today"; echo'
alias k='kubectl'
alias kaf='kubectl apply -f'
alias kcf='kubectl create -f'
alias kdp='kubectl delete pod'
alias kds='kubectl delete service'
alias kex='kubectl exec -it'
alias kgp='kubectl get pods'
alias kgn='kubectl get nodes'
alias kgs='kubectl get services'
alias kgd='kubectl get deployments'
alias klo='kubectl logs -f'
alias ks='kubectl -n kube-system'
alias ln='ln -i'
alias ls='eza'
alias lsblkid="lsblk -o name,label,fstype,size,uuid --noheadings"
alias lsd="ls -lF | grep '^d'"
alias lsf="ls -alF --classify --group-directories-first"
alias mount='mount |column -t'
alias mv='mv -iv'
alias mkdir='mkdir -pv'
alias myip='curl ipinfo.io/ip'
alias path="echo -e ${PATH//:/\\n}"
alias ports='sudo netstat -vatunpe'
alias psg='ps aux | grep -v grep | grep'
alias rcopy="rsync -av --progress -h"
alias rmove="rsync -av --progress -h --remove-source-files"
alias rupdate="rsync -avu --progress -h"
alias rsynchronize="rsync -avu --delete --progress -h"
alias tree="ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'"
alias untar='tar -zxvf'
alias wget='wget -c'